### ISSUE TITLE
MutableMultiDict

### ISSUE THREAD

**Issue by cathmonster** [aio-libs/aiorest#35]
aiorest-0.3.1-py3-none-any.whl

Running example from the web page and getting importError: cannot import name 'MutableMultiDict'

Am I having some other version...?

**Comment by asvetlov** [comment]
Thanks for report.
The reason is changes from new aiohttp 0.14 release.

I'll fix aiorest and publish new release but strongly recommend get rid of aiorest by switching to aiohttp.web.

If it isn't an option for you now -- that's ok, but for new projects please don't use aiorest.
Development of aiorest is stopped. I'll add the statement about that to README.

I've switched our pretty huge private project from aiorest to aiohttp.web in 2 days (we have good test coverage for our project to make this deep refactoring safe, though).

I've added `render_json` decorator (similar to `template` one from `aiohttp_jinja2` and refactored `aiorest.RESTError` exceptions to use `aiohttp.web` ones).

aiorest still has a features not implemented in aiohttp yet (sessions, CORS and security) but I'll transplant the code into libraries like aiohttp_session, aiohttp_cors and aiohttp_security very soon.

**Comment by asvetlov** [comment]
aiorest is updated to aiohttp 0.14, all tests passed.

If you still have problems -- please open a new issue.

**Comment by cathmonster** [comment]
Ok, thanks for the info.
I will not use it...

On Sun, Jan 18, 2015 at 4:04 PM, Andrew Svetlov <notifications@github.com>
wrote:

> aiorest is updated to aiohttp 0.14, all tests passed.
>
> If you still have problems -- please open a new issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aio-libs/aiorest/issues/35#issuecomment-70425841>.
>



-- 
Aleksandar Kacanski

**Comment by cathmonster** [comment]
Andrew,
Do you have simple example of chaining requests, because that is what I am trying to do.
I am trying to run one web service that would accept client push of json data and forward that one to the browser. Something like a proxy, but many rest clients (or http clients) pushing data and aiohttp.web serving those in realtime to browser via web.Response(text=raw)

maybe I am off the base here but I do have a sample that works fine like this:

r = yield from aiohttp.request('get', 'http://localhost/stats')
raw= yield from r.text()
return web.Response(text=raw)

What I would like to do is to setup a post or put service that would allow rest /http client to post string to url
something like bottle:
@route('/stats/msg', method='PUT')

def stat_handler( msg="" ):
....

then I should be able to use:

yield from aiohttp.request('post','http://localhost:8080/stats',data=raw)


Eventually, i will need to deal with long pooling or some other idea to keep updating browser in real time.
Any pointers appreciated ...

**Comment by asvetlov** [comment]
Sorry, I don't follow what help you waiting for. 
Your examples already have all required snippets.

**Comment by cathmonster** [comment]
Sorry Andrew, this was long before you answered my latest message ...
Thanks very much ...

On Tue, Jan 20, 2015 at 9:12 AM, Andrew Svetlov <notifications@github.com>
wrote:

> Sorry, I don't follow what help you waiting for.
> Your examples already have all required snippets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aio-libs/aiorest/issues/35#issuecomment-70658520>.
>



-- 
Aleksandar Kacanski
